from __future__ import annotations

import fnmatch
import re
from dataclasses import dataclass, field
from pathlib import PurePosixPath

from diff2tweet.config import RuntimeConfig
from diff2tweet.git import GitContext


@dataclass
class CommitFilterResult:
    subject: str
    kept: bool
    reason: str  # empty string if kept


@dataclass
class DiffSectionResult:
    path: str
    kept: bool
    reason: str  # empty string if kept


@dataclass
class BudgetUsage:
    project_chars: int = 0
    notes_chars: int = 0
    commit_chars: int = 0
    diff_chars: int = 0
    max_chars: int = 0

    @property
    def total_used(self) -> int:
        return self.project_chars + self.notes_chars + self.commit_chars + self.diff_chars


@dataclass
class FilterDiagnostics:
    commit_results: list[CommitFilterResult] = field(default_factory=list)
    diff_section_results: list[DiffSectionResult] = field(default_factory=list)
    budget: BudgetUsage = field(default_factory=BudgetUsage)


_BASE_PROMPT = """You write punchy, specific developer tweets about shipped code changes.

Rules:
- If a NOTES section is present in the context, treat it as the highest-priority source — the user added it specifically to guide this tweet. Prefer content from NOTES over the diff or commit messages.
- Pick ONE change — the single most interesting or user-visible thing in the context. Do not summarize every commit or combine multiple changes into one tweet.
- Lead with why it matters to the user — what they can now do, avoid, or understand. Do not open with what files changed or how it was implemented.
- Describe what changed for the user, not how it was implemented. Name the fix or feature; omit internal function names, class names, file paths, and implementation mechanisms unless they are the only way to express the change.
- The tweet MUST NOT exceed the character limit. Count your characters before returning. If the tweet is over the limit, cut implementation details first, then adjectives, then restructure until it fits.
- Do not use filler qualifiers or intensifiers — no 'way more', 'super', 'really', 'truly', 'just', 'actually', 'pretty much', or similar padding. Every word must earn its place.
- Be concrete about what changed; do not invent outcomes not supported by the context.
- Write like a real developer sharing a win, not a press release.
- Include forced hashtags only when they fit naturally.
- Do not use numbering, labels, or surrounding commentary.
"""

# --- PATCH DUAL STYLE ---
def _load_style(path: str) -> str:
    from pathlib import Path
    p = Path(path)
    if p.exists():
        txt = p.read_text(encoding='utf-8').strip()
        return f"
STYLE EXAMPLES (mimic rhythm, not copy):
{txt[:3000]}
" if txt else ""
    return ""

def build_prompt_for_style(config, git_context, notes_text, style: str) -> str:
    base = build_prompt(config, git_context, notes_text)
    if style == "viral":
        extra = _load_style(getattr(config, "style_viral_path", ".diff2tweet/STYLE_VIRAL.md"))
        extra += "
Instruction: Hook en CAPS, bullet ->, metriques chiffrees, ton RodmanAi rage-bait."
    else:
        extra = _load_style(getattr(config, "style_humble_path", ".diff2tweet/STYLE_HUMBLE.md"))
        extra += "
Instruction: Ton humble, 1ere personne, sobre, 'Je viens de ship', pas de CAPS."
    return base + "
" + extra
# -----------------------------

_AUTO_GENERATED_MARKERS = (
    "// auto-generated",
    "# generated by",
    "# do not edit",
    "/* eslint-disable */",
)

_USELESS_COMMIT_SUBJECTS = {"wip", "fix", "update", "misc", "cleanup", "typo", "temp"}

# Bot commit detection: subject prefixes and body signals that identify automated commits
_BOT_SUBJECT_PATTERNS = re.compile(
    r"^("
    r"(chore|build|ci)\(deps?\):"   # conventional: chore(deps): bump ...
    r"|bump\s+\S+\s+from\s+"        # dependabot PR title: Bump X from Y to Z
    r"|⬆\s+bump\s+"                 # emoji-prefixed bump
    r")",
    re.IGNORECASE,
)
_BOT_BODY_SIGNALS = ("updated-dependencies:", "dependabot[bot]")

# Git commit trailers to strip from message bodies before sending to the LLM
_TRAILER_PREFIXES = (
    "co-authored-by:",
    "co-authored by:",
    "signed-off-by:",
    "reviewed-by:",
    "acked-by:",
)

# GitHub Actions / CI skip directives that appear as standalone body lines
_CI_SKIP_RE = re.compile(
    r"^\[(?:skip[ -]ci|ci[ -]skip|no[ -]ci|skip[ -]actions)\]\s*$",
    re.IGNORECASE | re.MULTILINE,
)

# File path patterns that classify a diff section as documentation
_DOC_DIR_NAMES = frozenset(("docs", "doc", "documentation"))


def build_prompt(
    config: RuntimeConfig,
    git_context: GitContext,
    notes_text: str | None,
) -> str:
    """Assemble the final LLM prompt from repo context and config."""

    context_parts: list[str] = []
    project_section = _build_project_section(config)
    if project_section:
        context_parts.append(project_section)

    filtered_commit_messages = _filter_commit_messages(
        git_context.commit_messages, config.commit_subject_min_chars
    )
    sections = [
        ("NOTES", notes_text or ""),
        ("COMMIT MESSAGES", "\n".join(filtered_commit_messages)),
        ("FILTERED DIFF", _filter_diff(git_context.diff_text, config.diff_ignore_patterns, config.max_doc_diff_sections, config.max_doc_section_chars)),
    ]

    remaining_chars = config.context_max_chars - sum(len(part) for part in context_parts)
    for title, content in sections:
        if remaining_chars <= 0:
            break
        section_text = _format_section(title, content, remaining_chars)
        if not section_text:
            continue
        context_parts.append(section_text)
        remaining_chars -= len(section_text)

    hashtags_text = ", ".join(config.forced_hashtags) if config.forced_hashtags else "none"
    prompt_parts = [
        _BASE_PROMPT.strip(),
        'Return the single best tweet as JSON with this shape\n{"tweet": "..."}',
        f"Character limit: {config.character_limit}",
        f"Forced hashtags: {hashtags_text}",
        f"Commit range: {git_context.commit_range}",
    ]
    if config.custom_instructions:
        prompt_parts.append("Custom instructions:\n" + config.custom_instructions.strip())
    prompt_parts.append("Context:\n" + ("\n\n".join(context_parts) if context_parts else "(none)"))
    return "\n\n".join(prompt_parts)


def _build_project_section(config: RuntimeConfig) -> str:
    lines: list[str] = []
    if config.project_name:
        lines.append(f"Name: {config.project_name}")
    if config.project_summary:
        lines.append(f"Summary: {config.project_summary}")
    if config.project_audience:
        lines.append(f"Audience: {config.project_audience}")
    lines.append(f"Stage: {config.project_stage}")
    lines.append(f"Tone: {config.project_tone}")
    if config.project_key_terms:
        lines.append("Key terms: " + ", ".join(config.project_key_terms))
    if not lines:
        return ""
    return "## Project\n" + "\n".join(lines)


def _format_section(title: str, content: str, remaining_chars: int) -> str:
    content = content.strip()
    if not content:
        return ""

    header = f"## {title}\n"
    if remaining_chars <= len(header):
        return ""

    available = remaining_chars - len(header)
    trimmed_content = content[:available].rstrip()
    if not trimmed_content:
        return ""

    return header + trimmed_content


def _filter_commit_messages(messages: list[str], min_subject_chars: int) -> list[str]:
    filtered_messages: list[str] = []

    for message in messages:
        subject = _extract_commit_subject(message)
        if not subject:
            continue
        if _is_bot_commit(subject, message):
            continue

        normalized_subject = subject.strip().lower()
        if normalized_subject in _USELESS_COMMIT_SUBJECTS:
            continue
        if len(subject.strip()) < min_subject_chars:
            continue

        filtered_messages.append(_strip_git_trailers(message))

    return filtered_messages


def _extract_commit_subject(message: str) -> str:
    for line in message.splitlines():
        stripped = line.strip()
        if stripped:
            return stripped
    return ""


def _is_bot_commit(subject: str, body: str) -> bool:
    if _BOT_SUBJECT_PATTERNS.match(subject.strip()):
        return True
    body_lower = body.lower()
    return any(signal in body_lower for signal in _BOT_BODY_SIGNALS)


def _strip_git_trailers(message: str) -> str:
    """Remove CI skip directives and git trailers from a commit message body."""
    message = _CI_SKIP_RE.sub("", message)
    lines = message.splitlines()
    while lines and (
        not lines[-1].strip()
        or lines[-1].strip().lower().startswith(_TRAILER_PREFIXES)
    ):
        lines.pop()
    return "\n".join(lines).strip()


def _is_doc_path(path: str) -> bool:
    """Return True if this diff section path is primarily documentation."""
    normalized = path.replace("\\", "/").lower()
    pure = PurePosixPath(normalized)
    if any(part in _DOC_DIR_NAMES for part in pure.parts[:-1]):
        return True
    return normalized.endswith((".md", ".rst"))


def _truncate_doc_section(text: str, max_chars: int) -> str:
    """Truncate a doc diff section to at most max_chars, preserving the first line."""
    if max_chars == 0 or len(text) <= max_chars:
        return text
    lines = text.splitlines()
    header = lines[0] if lines else ""
    # Find the last newline boundary within max_chars
    truncated = text[:max_chars]
    last_newline = truncated.rfind("\n")
    if last_newline <= len(header):
        # Can't truncate nicely beyond the header; just return header with truncation marker
        return header + "\n[...truncated]"
    return text[:last_newline] + "\n[...truncated]"


def _filter_diff(diff_text: str, ignore_patterns: list[str], max_doc_sections: int, max_doc_section_chars: int = 0) -> str:
    if not diff_text.strip():
        return ""

    kept_sections: list[str] = []
    current_section: list[str] = []
    current_path: str | None = None
    doc_count: list[int] = [0]  # mutable counter passed by reference

    for line in diff_text.splitlines():
        if line.startswith("diff --git "):
            _append_diff_section(
                kept_sections, current_section, current_path,
                ignore_patterns, max_doc_sections, doc_count, max_doc_section_chars,
            )
            current_section = [line]
            current_path = _extract_diff_path(line)
            continue
        current_section.append(line)

    _append_diff_section(
        kept_sections, current_section, current_path,
        ignore_patterns, max_doc_sections, doc_count, max_doc_section_chars,
    )
    return "\n".join(kept_sections).strip()


def _append_diff_section(
    kept_sections: list[str],
    section_lines: list[str],
    path: str | None,
    ignore_patterns: list[str],
    max_doc_sections: int,
    doc_count: list[int],
    max_doc_section_chars: int = 0,
) -> None:
    if not section_lines:
        return
    if path and _matches_ignore_pattern(path, ignore_patterns):
        return
    if _is_pure_deletion_section(section_lines):
        return
    if _is_auto_generated_section(section_lines):
        return
    if path and _is_doc_path(path):
        if doc_count[0] >= max_doc_sections:
            return
        doc_count[0] += 1

    formatted_section = _format_diff_section(section_lines, path)
    if not formatted_section:
        return

    if path and _is_doc_path(path):
        formatted_section = _truncate_doc_section(formatted_section, max_doc_section_chars)

    kept_sections.append(formatted_section)


def _extract_diff_path(diff_header: str) -> str | None:
    parts = diff_header.split()
    if len(parts) < 4:
        return None

    for candidate in reversed(parts[-2:]):
        if candidate.startswith("b/"):
            return candidate[2:]
        if candidate.startswith("a/"):
            return candidate[2:]
    return None


def _matches_ignore_pattern(path: str, patterns: list[str]) -> bool:
    normalized = path.replace("\\", "/")
    pure_path = PurePosixPath(normalized)
    for pattern in patterns:
        if pure_path.match(pattern) or fnmatch.fnmatch(normalized, pattern):
            return True
    return False



def _is_pure_deletion_section(section_lines: list[str]) -> bool:
    has_hunk_content = False
    has_added_line = False
    has_deleted_line = False

    for line in section_lines:
        if not line:
            continue
        if line.startswith(("diff --git ", "--- ", "+++ ", "@@ ")):
            continue
        if line.startswith("+"):
            has_hunk_content = True
            has_added_line = True
            continue
        if line.startswith("-"):
            has_hunk_content = True
            has_deleted_line = True

    return has_hunk_content and has_deleted_line and not has_added_line



def _is_auto_generated_section(section_lines: list[str]) -> bool:
    for line in section_lines:
        if not line:
            continue
        if line.startswith("diff --git "):
            continue
        if line.startswith(("--- ", "+++ ", "@@ ")):
            continue
        if not line.startswith(("+", "-", " ")):
            continue

        content = line[1:].strip().lower()
        if not content:
            continue

        return any(marker in content for marker in _AUTO_GENERATED_MARKERS)

    return False


def _format_diff_section(section_lines: list[str], path: str | None) -> str:
    header_path = path or _extract_diff_path(section_lines[0]) or "unknown"
    display_name = PurePosixPath(header_path.replace("\\", "/")).name or header_path
    content_lines = [
        line
        for line in section_lines
        if line.startswith(("+", "-", " ")) and not line.startswith(("+++ ", "--- "))
    ]
    if not content_lines:
        return ""
    return "\n".join([f"# {display_name}", *content_lines])


def build_prompt_with_diagnostics(
    config: RuntimeConfig,
    git_context: GitContext,
    notes_text: str | None,
) -> tuple[str, FilterDiagnostics]:
    """Assemble the final LLM prompt and return it alongside filter diagnostics."""

    diagnostics = FilterDiagnostics()
    diagnostics.budget.max_chars = config.context_max_chars

    context_parts: list[str] = []
    project_section = _build_project_section(config)
    if project_section:
        context_parts.append(project_section)
        diagnostics.budget.project_chars = len(project_section)

    filtered_commit_messages, commit_results = _filter_commit_messages_with_diagnostics(
        git_context.commit_messages, config.commit_subject_min_chars
    )
    diagnostics.commit_results = commit_results

    filtered_diff, diff_section_results = _filter_diff_with_diagnostics(
        git_context.diff_text, config.diff_ignore_patterns, config.max_doc_diff_sections, config.max_doc_section_chars
    )
    diagnostics.diff_section_results = diff_section_results

    sections = [
        ("NOTES", notes_text or ""),
        ("COMMIT MESSAGES", "\n".join(filtered_commit_messages)),
        ("FILTERED DIFF", filtered_diff),
    ]

    remaining_chars = config.context_max_chars - sum(len(part) for part in context_parts)
    for title, content in sections:
        if remaining_chars <= 0:
            break
        section_text = _format_section(title, content, remaining_chars)
        if not section_text:
            continue
        context_parts.append(section_text)
        section_len = len(section_text)
        remaining_chars -= section_len
        if title == "NOTES":
            diagnostics.budget.notes_chars = section_len
        elif title == "COMMIT MESSAGES":
            diagnostics.budget.commit_chars = section_len
        elif title == "FILTERED DIFF":
            diagnostics.budget.diff_chars = section_len

    hashtags_text = ", ".join(config.forced_hashtags) if config.forced_hashtags else "none"
    prompt_parts = [
        _BASE_PROMPT.strip(),
        'Return the single best tweet as JSON with this shape\n{"tweet": "..."}',
        f"Character limit: {config.character_limit}",
        f"Forced hashtags: {hashtags_text}",
        f"Commit range: {git_context.commit_range}",
    ]
    if config.custom_instructions:
        prompt_parts.append("Custom instructions:\n" + config.custom_instructions.strip())
    prompt_parts.append("Context:\n" + ("\n\n".join(context_parts) if context_parts else "(none)"))

    return "\n\n".join(prompt_parts), diagnostics


def _filter_commit_messages_with_diagnostics(
    messages: list[str], min_subject_chars: int
) -> tuple[list[str], list[CommitFilterResult]]:
    results: list[CommitFilterResult] = []
    kept: list[str] = []

    for message in messages:
        subject = _extract_commit_subject(message)
        if not subject:
            results.append(CommitFilterResult("(empty)", False, "no subject line"))
            continue
        if _is_bot_commit(subject, message):
            results.append(CommitFilterResult(subject, False, "bot/dependency commit"))
            continue

        normalized = subject.strip().lower()
        if normalized in _USELESS_COMMIT_SUBJECTS:
            results.append(CommitFilterResult(subject, False, "junk subject"))
            continue
        if len(subject.strip()) < min_subject_chars:
            results.append(
                CommitFilterResult(
                    subject, False, f"too short ({len(subject.strip())} < {min_subject_chars})"
                )
            )
            continue

        results.append(CommitFilterResult(subject, True, ""))
        kept.append(_strip_git_trailers(message))

    return kept, results


def _filter_diff_with_diagnostics(
    diff_text: str, ignore_patterns: list[str], max_doc_sections: int, max_doc_section_chars: int = 0
) -> tuple[str, list[DiffSectionResult]]:
    if not diff_text.strip():
        return "", []

    kept_sections: list[str] = []
    section_results: list[DiffSectionResult] = []
    current_section: list[str] = []
    current_path: str | None = None
    doc_count: list[int] = [0]

    def process_section() -> None:
        if not current_section:
            return
        display = current_path or "unknown"

        if current_path and _matches_ignore_pattern(current_path, ignore_patterns):
            section_results.append(DiffSectionResult(display, False, "matches ignore pattern"))
            return
        if _is_pure_deletion_section(current_section):
            section_results.append(DiffSectionResult(display, False, "pure deletion"))
            return
        if _is_auto_generated_section(current_section):
            section_results.append(DiffSectionResult(display, False, "auto-generated file"))
            return
        if current_path and _is_doc_path(current_path):
            if doc_count[0] >= max_doc_sections:
                section_results.append(DiffSectionResult(display, False, "doc section cap reached"))
                return
            doc_count[0] += 1
        formatted = _format_diff_section(current_section, current_path)
        if not formatted:
            section_results.append(DiffSectionResult(display, False, "no content lines"))
            return
        if current_path and _is_doc_path(current_path):
            formatted = _truncate_doc_section(formatted, max_doc_section_chars)
        kept_sections.append(formatted)
        section_results.append(DiffSectionResult(display, True, ""))

    for line in diff_text.splitlines():
        if line.startswith("diff --git "):
            process_section()
            current_section = [line]
            current_path = _extract_diff_path(line)
            continue
        current_section.append(line)

    process_section()
    return "\n".join(kept_sections).strip(), section_results

